Fix eisbrecher regressin which broke parsing of razor config
/usr/lib/ruby/vendor_ruby/json/common.rb:148:in `parse': 394: unexpected token at 'config] <- undefined method `mirror_port' for #<ProjectRazor::Config::Server:0x7fa057218b18> (JSON::ParserError)
{"slice":"ProjectRazor::Slice","http_err_code":404,"result":"InvalidSlice"}
'
        from /usr/lib/ruby/vendor_ruby/json/common.rb:148:in `parse'
        from /opt/razor/bin/razor_daemon.rb:123:in `get_config'
        from /opt/razor/bin/razor_daemon.rb:271